# Generated by Django 4.0.6 on 2022-07-26 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0003_customer_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='user',
        ),
        migrations.AddField(
            model_name='customer',
            name='password1',
            field=models.CharField(default=123, max_length=50),
        ),
        migrations.AddField(
            model_name='customer',
            name='password2',
            field=models.CharField(default=123, max_length=50),
        ),
    ]
