# Generated by Django 4.0.6 on 2022-07-27 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0006_customer_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='id',
        ),
        migrations.AlterField(
            model_name='order',
            name='transactionID',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
